//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YZMYapimiProjesi.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlimSatimIslemler
    {
        public int Id { get; set; }
        public string AliciAdi { get; set; }
        public int AliciId { get; set; }
        public string SaticiAdi { get; set; }
        public int SaticiId { get; set; }
        public double Fiyat { get; set; }
        public int Miktar { get; set; }
        public string urnAdi { get; set; }
        public System.DateTime islemZamani { get; set; }
    }
}
