//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YZMYapimiProjesi.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class BeklyenIslemlerTable
    {
        public int Id { get; set; }
        public int AliciID { get; set; }
        public string UrunAdi { get; set; }
        public int UrunMiktari { get; set; }
        public double UrunFiyati { get; set; }
    
        public virtual KullaniciTable KullaniciTable { get; set; }
    }
}
