//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YZMYapimiProjesi.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaticiVarliklari
    {
        public int Id { get; set; }
        public int KullaniciId { get; set; }
        public string urnAdi { get; set; }
        public int urnMiktari { get; set; }
        public double urnFiyat { get; set; }
        public int SaticiStatueId { get; set; }
    
        public virtual KullaniciTable KullaniciTable { get; set; }
    }
}
